spring.application.name=taskflow-backend


spring.data.mongodb.uri=mongodb+srv://divyanshu983770_db_user:Anu0834255@taskflow.djnzcha.mongodb.net/taskflow?retryWrites=true&w=majority


server.port=8080


jwt.secret=ChangeThisToALongRandomSecretKeyForProductionUseAtLeast256BitsLong
jwt.expiration-ms=86400000


logging.level.org.springframework.security=INFO
logging.level.com.taskflow=DEBUG
// loggin krne kai lia
//mvn spring-boot:run 
